from __future__ import annotations

APP_NAME = "Helm-Path"
CHALLENGES_DIRNAME = "challenges"
METADATA_FILENAME = ".metadata.json"
WORKING_NOTES_FILENAME = "WORKING_NOTES.md"
FAILURES_FILENAME = "FAILURES.md"
AUDIT_DIRNAME = ".ffr"
AUDIT_DB_FILENAME = "audit.db"
REPORT_MANIFEST_FILENAME = "report_manifest.json"
GRAPH_DIRNAME = "graph"
GRAPH_MANIFEST_FILENAME = "manifest.json"
GRAPH_JSON_FILENAME = "graph.json"
GRAPH_COMMANDS_FILENAME = "commands.json"
GRAPH_HTML_FILENAME = "index.html"
COMMAND_LOG_FILENAME = "commands.jsonl"
COMMAND_MARKER_START = "__HELM_PATH_CMD_START__"
COMMAND_MARKER_END = "__HELM_PATH_CMD_END__"

FULL_IMAGE_TAG = "helm-path:kali"
LITE_IMAGE_TAG = "helm-path:lite"
DEFAULT_MODEL = "llama3.2:3b"
PROMPT_VERSION = "ffr-report-v1"
GRAPH_PROMPT_VERSION = "ffr-graph-v1"
